#  opnjdk 11 이미지를 가지고 온다
FROM openjdk:11-jdk-slim 

#  터미널이 실행되는 위치를 설정한다.
# WORKDIR /var/currunt/app

# #  ./가 되는건 workdir 설정을 해서
# COPY ./deploy/aws-v3-0.0.3.jar ./application.jar

# # 상수. 변경이 안됨. 
# ENTRYPOINT ["java", "-jar", "./application.jar"]

# #  바꿀 수 있는 옵션, 변수
# CMD ["--server.port=3000"]

